apiVersion: v1
kind: Pod
metadata:
    name: auto-pod
    labels: 
        zone: dev
        version: v1
spec:
    containers:
    - name: auto-ctr
      image: refapp/automation:1.0
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort : 8080
  