apiVersion: v1
kind: Pod
metadata:
    name: hello-pod
    labels: 
        zone: dev
        version: v1
spec:
  #hostNetwork: true
  containers:
    - name: hello-ctr
      image: nginxdemos/hello
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort : 80
  

