spring:
  datasource:
    url: jdbc:mysql://localhost/friends
    username: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #update or create => Need to understand reason.
      ddl-auto: update
    show-sql: true