apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
     matchLabels:
      app: hello-world
  template:
    metadata:
        name: hello-pod
        labels: 
          app: hello-world
          zone: dev
          version: v3
    spec:
      containers:
        - name: hello-ctr
          image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort : 80
