apiVersion: v1
kind: ReplicationController 
metadata:
  name: hello-rc
spec:
  replicas: 4
  selector:
    app: hello-world
  template:
    metadata:
        name: hello-pod
        labels: 
          app: hello-world
          zone: dev
          version: v1
    spec:
      containers:
        - name: hello-ctr
          image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort : 80
