apiVersion: v1
kind: Service 
metadata:
  name: hello-svc
spec:
  type: NodePort
  ports:
    - port: 80 #Export on container
      nodePort: 30001
      protocol: TCP
  selector:
      app: hello-world